title: "Squid mailing lists archive"
description: "Squid Web Cache public mailing list archive"
url: https://ml-archives.squid-cache.org/
plugins:
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-optional-front-matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
